# Generated by Django 3.2.12 on 2022-05-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctv',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cctv',
            name='latitude',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cctv',
            name='longitude',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
