# Generated by Django 3.2.12 on 2022-05-02 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0003_auto_20220502_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cctv',
            old_name='longitude',
            new_name='longtitude',
        ),
    ]
