# Generated by Django 3.2.12 on 2022-05-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0004_rename_longitude_cctv_longtitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('longtitude', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
